---
default:
  tags:
    - shared-small
  interruptible: true

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - check
  - test

include:
  - local: ci/setup.yml
  - local: ci/rules.yml
  - local: ci/lint.yml
  - local: ci/test.yml
  - local: ci/fuzz.yml
  - component: gitlab.protontech.ch/proton/devops/cicd-components/kits/devsecops/go@~latest
    inputs:
      stage: check
