// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/ProtonMail/gluon/internal/db_impl/ent_db/internal"
)

// The DeletedSubscriptionFunc type is an adapter to allow the use of ordinary
// function as DeletedSubscription mutator.
type DeletedSubscriptionFunc func(context.Context, *internal.DeletedSubscriptionMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f DeletedSubscriptionFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.DeletedSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.DeletedSubscriptionMutation", m)
}

// The MailboxFunc type is an adapter to allow the use of ordinary
// function as Mailbox mutator.
type MailboxFunc func(context.Context, *internal.MailboxMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MailboxFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MailboxMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MailboxMutation", m)
}

// The MailboxAttrFunc type is an adapter to allow the use of ordinary
// function as MailboxAttr mutator.
type MailboxAttrFunc func(context.Context, *internal.MailboxAttrMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MailboxAttrFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MailboxAttrMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MailboxAttrMutation", m)
}

// The MailboxFlagFunc type is an adapter to allow the use of ordinary
// function as MailboxFlag mutator.
type MailboxFlagFunc func(context.Context, *internal.MailboxFlagMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MailboxFlagFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MailboxFlagMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MailboxFlagMutation", m)
}

// The MailboxPermFlagFunc type is an adapter to allow the use of ordinary
// function as MailboxPermFlag mutator.
type MailboxPermFlagFunc func(context.Context, *internal.MailboxPermFlagMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MailboxPermFlagFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MailboxPermFlagMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MailboxPermFlagMutation", m)
}

// The MessageFunc type is an adapter to allow the use of ordinary
// function as Message mutator.
type MessageFunc func(context.Context, *internal.MessageMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MessageFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MessageMutation", m)
}

// The MessageFlagFunc type is an adapter to allow the use of ordinary
// function as MessageFlag mutator.
type MessageFlagFunc func(context.Context, *internal.MessageFlagMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f MessageFlagFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.MessageFlagMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.MessageFlagMutation", m)
}

// The UIDFunc type is an adapter to allow the use of ordinary
// function as UID mutator.
type UIDFunc func(context.Context, *internal.UIDMutation) (internal.Value, error)

// Mutate calls f(ctx, m).
func (f UIDFunc) Mutate(ctx context.Context, m internal.Mutation) (internal.Value, error) {
	if mv, ok := m.(*internal.UIDMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *internal.UIDMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, internal.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m internal.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m internal.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m internal.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op internal.Op) Condition {
	return func(_ context.Context, m internal.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m internal.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m internal.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m internal.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk internal.Hook, cond Condition) internal.Hook {
	return func(next internal.Mutator) internal.Mutator {
		return internal.MutateFunc(func(ctx context.Context, m internal.Mutation) (internal.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, internal.Delete|internal.Create)
func On(hk internal.Hook, op internal.Op) internal.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, internal.Update|internal.UpdateOne)
func Unless(hk internal.Hook, op internal.Op) internal.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) internal.Hook {
	return func(internal.Mutator) internal.Mutator {
		return internal.MutateFunc(func(context.Context, internal.Mutation) (internal.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []internal.Hook {
//		return []internal.Hook{
//			Reject(internal.Delete|internal.Update),
//		}
//	}
func Reject(op internal.Op) internal.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []internal.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...internal.Hook) Chain {
	return Chain{append([]internal.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() internal.Hook {
	return func(mutator internal.Mutator) internal.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...internal.Hook) Chain {
	newHooks := make([]internal.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
