// Code generated by ent, DO NOT EDIT.

package mailboxflag

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ProtonMail/gluon/internal/db_impl/ent_db/internal/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldLTE(FieldID, id))
}

// Value applies equality check predicate on the "Value" field. It's identical to ValueEQ.
func Value(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldEQ(FieldValue, v))
}

// ValueEQ applies the EQ predicate on the "Value" field.
func ValueEQ(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "Value" field.
func ValueNEQ(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "Value" field.
func ValueIn(vs ...string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "Value" field.
func ValueNotIn(vs ...string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "Value" field.
func ValueGT(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "Value" field.
func ValueGTE(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "Value" field.
func ValueLT(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "Value" field.
func ValueLTE(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "Value" field.
func ValueContains(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "Value" field.
func ValueHasPrefix(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "Value" field.
func ValueHasSuffix(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "Value" field.
func ValueEqualFold(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "Value" field.
func ValueContainsFold(v string) predicate.MailboxFlag {
	return predicate.MailboxFlag(sql.FieldContainsFold(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailboxFlag) predicate.MailboxFlag {
	return predicate.MailboxFlag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailboxFlag) predicate.MailboxFlag {
	return predicate.MailboxFlag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailboxFlag) predicate.MailboxFlag {
	return predicate.MailboxFlag(func(s *sql.Selector) {
		p(s.Not())
	})
}
