// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProtonMail/gluon/reporter (interfaces: Reporter)
//
// Generated by this command:
//
//	mockgen --package mock_reporter github.com/ProtonMail/gluon/reporter Reporter
//

// Package mock_reporter is a generated GoMock package.
package mock_reporter

import (
	reflect "reflect"

	reporter "github.com/ProtonMail/gluon/reporter"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// ReportException mocks base method.
func (m *MockReporter) ReportException(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportException", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportException indicates an expected call of ReportException.
func (mr *MockReporterMockRecorder) ReportException(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportException", reflect.TypeOf((*MockReporter)(nil).ReportException), arg0)
}

// ReportExceptionWithContext mocks base method.
func (m *MockReporter) ReportExceptionWithContext(arg0 any, arg1 reporter.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportExceptionWithContext", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportExceptionWithContext indicates an expected call of ReportExceptionWithContext.
func (mr *MockReporterMockRecorder) ReportExceptionWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportExceptionWithContext", reflect.TypeOf((*MockReporter)(nil).ReportExceptionWithContext), arg0, arg1)
}

// ReportMessage mocks base method.
func (m *MockReporter) ReportMessage(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportMessage indicates an expected call of ReportMessage.
func (mr *MockReporterMockRecorder) ReportMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportMessage", reflect.TypeOf((*MockReporter)(nil).ReportMessage), arg0)
}

// ReportMessageWithContext mocks base method.
func (m *MockReporter) ReportMessageWithContext(arg0 string, arg1 reporter.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportMessageWithContext", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportMessageWithContext indicates an expected call of ReportMessageWithContext.
func (mr *MockReporterMockRecorder) ReportMessageWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportMessageWithContext", reflect.TypeOf((*MockReporter)(nil).ReportMessageWithContext), arg0, arg1)
}

// ReportMessageWithContextAndTags mocks base method.
func (m *MockReporter) ReportMessageWithContextAndTags(arg0 string, arg1 reporter.Context, arg2 reporter.Tags) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportMessageWithContextAndTags", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportMessageWithContextAndTags indicates an expected call of ReportMessageWithContextAndTags.
func (mr *MockReporterMockRecorder) ReportMessageWithContextAndTags(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportMessageWithContextAndTags", reflect.TypeOf((*MockReporter)(nil).ReportMessageWithContextAndTags), arg0, arg1, arg2)
}

// ReportWarningWithContext mocks base method.
func (m *MockReporter) ReportWarningWithContext(arg0 string, arg1 reporter.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportWarningWithContext", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportWarningWithContext indicates an expected call of ReportWarningWithContext.
func (mr *MockReporterMockRecorder) ReportWarningWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportWarningWithContext", reflect.TypeOf((*MockReporter)(nil).ReportWarningWithContext), arg0, arg1)
}
