// Code generated by ent, DO NOT EDIT.

package uidvalidity

const (
	// Label holds the string label denoting the uidvalidity type in the database.
	Label = "uid_validity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUIDValidity holds the string denoting the uidvalidity field in the database.
	FieldUIDValidity = "uid_validity"
	// Table holds the table name of the uidvalidity in the database.
	Table = "uid_validities"
)

// Columns holds all SQL columns for uidvalidity fields.
var Columns = []string{
	FieldID,
	FieldUIDValidity,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
