// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Mailbox is the predicate function for mailbox builders.
type Mailbox func(*sql.Selector)

// MailboxAttr is the predicate function for mailboxattr builders.
type MailboxAttr func(*sql.Selector)

// MailboxFlag is the predicate function for mailboxflag builders.
type MailboxFlag func(*sql.Selector)

// MailboxPermFlag is the predicate function for mailboxpermflag builders.
type MailboxPermFlag func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// MessageFlag is the predicate function for messageflag builders.
type MessageFlag func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// UID is the predicate function for uid builders.
type UID func(*sql.Selector)
