// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ProtonMail/gluon/imap"
	"github.com/ProtonMail/gluon/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// MailboxID applies equality check predicate on the "MailboxID" field. It's identical to MailboxIDEQ.
func MailboxID(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMailboxID), vc))
	})
}

// RemoteID applies equality check predicate on the "RemoteID" field. It's identical to RemoteIDEQ.
func RemoteID(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRemoteID), vc))
	})
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// MailboxIDEQ applies the EQ predicate on the "MailboxID" field.
func MailboxIDEQ(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMailboxID), vc))
	})
}

// MailboxIDNEQ applies the NEQ predicate on the "MailboxID" field.
func MailboxIDNEQ(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMailboxID), vc))
	})
}

// MailboxIDIn applies the In predicate on the "MailboxID" field.
func MailboxIDIn(vs ...imap.InternalMailboxID) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = uint64(vs[i])
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldMailboxID), v...))
	})
}

// MailboxIDNotIn applies the NotIn predicate on the "MailboxID" field.
func MailboxIDNotIn(vs ...imap.InternalMailboxID) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = uint64(vs[i])
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldMailboxID), v...))
	})
}

// MailboxIDGT applies the GT predicate on the "MailboxID" field.
func MailboxIDGT(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMailboxID), vc))
	})
}

// MailboxIDGTE applies the GTE predicate on the "MailboxID" field.
func MailboxIDGTE(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMailboxID), vc))
	})
}

// MailboxIDLT applies the LT predicate on the "MailboxID" field.
func MailboxIDLT(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMailboxID), vc))
	})
}

// MailboxIDLTE applies the LTE predicate on the "MailboxID" field.
func MailboxIDLTE(v imap.InternalMailboxID) predicate.Subscription {
	vc := uint64(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMailboxID), vc))
	})
}

// RemoteIDEQ applies the EQ predicate on the "RemoteID" field.
func RemoteIDEQ(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDNEQ applies the NEQ predicate on the "RemoteID" field.
func RemoteIDNEQ(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDIn applies the In predicate on the "RemoteID" field.
func RemoteIDIn(vs ...imap.MailboxID) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldRemoteID), v...))
	})
}

// RemoteIDNotIn applies the NotIn predicate on the "RemoteID" field.
func RemoteIDNotIn(vs ...imap.MailboxID) predicate.Subscription {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldRemoteID), v...))
	})
}

// RemoteIDGT applies the GT predicate on the "RemoteID" field.
func RemoteIDGT(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDGTE applies the GTE predicate on the "RemoteID" field.
func RemoteIDGTE(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDLT applies the LT predicate on the "RemoteID" field.
func RemoteIDLT(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDLTE applies the LTE predicate on the "RemoteID" field.
func RemoteIDLTE(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDContains applies the Contains predicate on the "RemoteID" field.
func RemoteIDContains(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "RemoteID" field.
func RemoteIDHasPrefix(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "RemoteID" field.
func RemoteIDHasSuffix(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDIsNil applies the IsNil predicate on the "RemoteID" field.
func RemoteIDIsNil() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldRemoteID)))
	})
}

// RemoteIDNotNil applies the NotNil predicate on the "RemoteID" field.
func RemoteIDNotNil() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldRemoteID)))
	})
}

// RemoteIDEqualFold applies the EqualFold predicate on the "RemoteID" field.
func RemoteIDEqualFold(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRemoteID), vc))
	})
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "RemoteID" field.
func RemoteIDContainsFold(v imap.MailboxID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRemoteID), vc))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		p(s.Not())
	})
}
