inputs:
   artifact-name:
     required: true

runs:
  using: "composite"

  steps:
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.0

    - name: Set up MinGW
      if: ${{ runner.os == 'Windows' }}
      uses: egor-tensin/setup-mingw@v2

    - name: Bootstrap vcpkg
      run: internal/parser/extern/vcpkg/bootstrap-vcpkg.sh
      shell: bash

    - name: Load vcpkg build cache (windows)
      uses: actions/cache@v3
      if: ${{ runner.os == 'Windows' }}
      with:
        path: ~/AppData/Local/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('internal/parser/vcpkg.json') }}-v2

    - name: Load vcpkg build cache (not windows)
      uses: actions/cache@v3
      if: ${{ runner.os != 'Windows' }}
      with:
        path: ~/.cache/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('internal/parser/vcpkg.json') }}-v2

    - name: Configure CMake project (windows)
      if: ${{ runner.os == 'Windows' }}
      run: cmake -B build -S internal/parser -G Ninja -W no-dev -D CMAKE_BUILD_TYPE=Release -D VCPKG_TARGET_TRIPLET=x64-mingw-static 
      shell: bash

    - name: Configure CMake project (not windows)
      if: ${{ runner.os != 'Windows' }}
      run: cmake -B build -S internal/parser -G Ninja -W no-dev -D CMAKE_BUILD_TYPE=Release 
      shell: bash

    - name: Delete the old parser
      run: rm -r internal/parser/lib
      shell: bash

    - name: Build the new parser
      run: cmake --build build
      shell: bash

    - name: Test the new parser
      run: ctest --test-dir build
      shell: bash

    - name: Upload static libs
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: internal/parser/lib/*
