name: Build, test and release

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: changed
        uses: tj-actions/changed-files@v21
        with:
          files: internal/parser

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: check
    steps:
      - name: Get sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build parser if modified
        if: needs.check.outputs.changed == 'true'
        uses: ./.github/actions/build-parser
        with:
          artifact-name: ${{ matrix.os }}-libs

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Remove old static libs if modified
        if: needs.check.outputs.changed == 'true'
        run: rm -r internal/parser/lib

      - name: Download new static libs if modified
        if: needs.check.outputs.changed == 'true'
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}-libs
          path: internal/parser/lib

      - name: Run go vet
        run: go vet $(go list ./... | grep -v internal/parser)

      - name: Run tests
        run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Remove old static libs
        if: needs.check.outputs.changed == 'true'
        run: rm -r internal/parser/lib

      - name: Download linux static libs
        if: needs.check.outputs.changed == 'true'
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-libs
          path: internal/parser/lib

      - name: Download macOS static libs
        if: needs.check.outputs.changed == 'true'
        uses: actions/download-artifact@v3
        with:
          name: macos-12-libs
          path: internal/parser/lib

      - name: Download windows static libs
        if: needs.check.outputs.changed == 'true'
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-libs
          path: internal/parser/lib

      - uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
