name: Release workflow

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
